apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  # Ini Database URL rahasia kita
  database-url: "postgresql://minirestoo_user:secretpassword@db-service.default.svc.cluster.local:5432/minirestoo_db"