server {
    listen 80;

    # 1. Product Service
    location /api/products {
        proxy_pass http://product-management:3002/api/products;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 2. Inventory Service
    location /api/inventory {
        proxy_pass http://inventory-management:3001/api/inventory;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. Orders (KE PRODUCT MANAGEMENT)
    location /api/orders {
        proxy_pass http://product-management:3002/api/orders;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 4. Error Page
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}